# tproxy-port: 1536
# allow-lan: true
mode: rule
log-level: error
ipv6: false
unified-delay: true
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
tun:
  enable: true
  stack: system
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true
dns:
  enable: true
  respect-rules: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.0/15
  fake-ip-filter:
    - "*"
    - "+.lan"
    - "+.local"
  default-nameserver:
    - "https://223.5.5.5/dns-query"
  nameserver:
    - "https://dns.cloudflare.com/dns-query"
    - "https://dns.google/dns-query"
  proxy-server-nameserver:
    - "https://doh.pub/dns-query"
  nameserver-policy:
    "rule-set:ChinaMax,ChinaMax_Domain,Lan":
      - "https://doh.pub/dns-query"
      - "https://dns.alidns.com/dns-query"
    "rule-set:AWAvenue_Ads,Advertising,Advertising_Domain":
      - "rcode://success"
proxies:
- name: "dns-out"
  type: dns
proxy-providers:
  大陆钉钉:
    type: http
    url: ""
    interval: 86400
    health-check:
      enable: true
      url: "https://connectivitycheck.platform.hicloud.com/generate_204"
      interval: 3600
      lazy: true
  海外钉钉:
    type: http
    url: ""
    interval: 86400
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 3600
      lazy: true
  大陆云盘:
    type: http
    url: ""
    interval: 86400
    health-check:
      enable: true
      url: "https://connectivitycheck.platform.hicloud.com/generate_204"
      interval: 3600
      lazy: true
  海外云盘:
    type: http
    url: ""
    interval: 86400
    health-check:
      enable: true
      url: "https://www.google.com/generate_204"
      interval: 3600
      lazy: true
proxy-groups:
  - name: "大陆出站"
    type: select
    proxies:
      - "大陆钉钉"
      - "大陆云盘"
      - "DIRECT"
      - "PASS"
  - name: "大陆钉钉"
    type: fallback
    url: "https://connectivitycheck.platform.hicloud.com/generate_204"
    interval: 600
    lazy: true
    max-failed-times: 3
    use:
      - "大陆钉钉"
  - name: "大陆云盘"
    type: fallback
    url: "https://connectivitycheck.platform.hicloud.com/generate_204"
    interval: 600
    lazy: true
    max-failed-times: 3
    use:
      - "大陆云盘"
  - name: "广告拦截"
    type: select
    proxies:
      - "REJECT"
      - "PASS"
  - name: "游戏分流"
    type: select
    proxies:
      - "PASS"
      - "DIRECT"
  - name: "海外出站"
    type: select
    proxies:
      - "海外钉钉"
      - "海外云盘"
  - name: "海外钉钉"
    type: fallback
    url: "https://www.google.com/generate_204"
    interval: 600
    lazy: true
    max-failed-times: 3
    use:
      - "海外钉钉"
  - name: "海外云盘"
    type: fallback
    url: "https://www.google.com/generate_204"
    interval: 600
    lazy: true
    max-failed-times: 3
    use:
      - "海外云盘"
rule-providers:
  AWAvenue_Ads:
    type: http
    url: "https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main//Filters/AWAvenue-Ads-Rule-Clash.yaml"
    interval: 86400
    proxy: 海外出站
    behavior: domain
    format: yaml
  Advertising:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising.yaml"
    interval: 86400
    proxy: 海外出站
    behavior: classical
    format: yaml
  Advertising_Domain:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.txt"
    interval: 86400
    proxy: 海外出站
    behavior: domain
    format: text
  Google:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
    interval: 86400
    proxy: 海外出站
    behavior: classical
    format: yaml
  ChinaMax:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax.yaml"
    interval: 86400
    proxy: 海外出站
    behavior: classical
    format: yaml
  ChinaMax_Domain:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_Domain.txt"
    interval: 86400
    proxy: 海外出站
    behavior: domain
    format: text
  ChinaMax_IP_No_IPv6:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP_No_IPv6.txt"
    interval: 86400
    proxy: 海外出站
    behavior: ipcidr
    format: text
  Lan:
    type: http
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
    interval: 86400
    proxy: 海外出站
    behavior: classical
    format: yaml
rules:
  - DST-PORT,53,dns-out
  - RULE-SET,AWAvenue_Ads,广告拦截
  - RULE-SET,Advertising,广告拦截
  - RULE-SET,Advertising_Domain,广告拦截
  - AND,((NETWORK,UDP),(DST-PORT,3478)),REJECT-DROP
  - AND,((NETWORK,UDP),(DST-PORT,443)),REJECT-DROP
  - DOMAIN,mcdn.bilivideo.cn,REJECT-DROP
  - DOMAIN,tracker.biliapi.net,REJECT-DROP
  - DOMAIN-REGEX,stun(.*)\.chat\.bilibili\.com,REJECT-DROP
  - DOMAIN-REGEX,(.*)-p2p-(.*)\.chat\.bilibili\.com,REJECT-DROP
  - DOMAIN-REGEX,(.*)\.v(.*)d\.szbdyd\.com,REJECT-DROP
  - DOMAIN-REGEX,(.*)-live-tracker-(.*)\.chat\.bilibili\.com,REJECT-DROP
  - IP-CIDR,203.107.1.0/24,REJECT-DROP
  - RULE-SET,Google,海外出站
  - DOMAIN,www.bing.com,海外出站
  - AND,((PROCESS-NAME,com.tencent.tmgp.sgame),(NETWORK,UDP)),游戏分流
  - AND,((PROCESS-NAME,com.tencent.tmgp.cod),(NETWORK,UDP)),游戏分流
  - AND,((PROCESS-NAME,com.miHoYo.Yuanshen),(NETWORK,UDP)),游戏分流
  - AND,((PROCESS-NAME,com.netease.l22),(NETWORK,UDP)),游戏分流
  - RULE-SET,ChinaMax,大陆出站
  - RULE-SET,ChinaMax_Domain,大陆出站
  - RULE-SET,ChinaMax_IP_No_IPv6,大陆出站
  - RULE-SET,Lan,DIRECT,no-resolve
  - MATCH,海外出站
  - MATCH,REJECT